version: "2"
services:
  producer-live:
    build:
      context: producer_live/
    network_mode: host
    
  #producer-static:
   # build:
    #  context: producer_static/
    #network_mode: host
  
  consumer:
    build:
      context: consumer/
    deploy:
      mode: replicated
      replicas: 3 
    network_mode: host



  
